
package sud.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductsManager", targetNamespace = "http://webservices.sud/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductsManager {


    /**
     * 
     * @param productId
     * @return
     *     returns double
     * @throws NoSuchProductException_Exception
     */
    @WebMethod
    @WebResult(name = "price", partName = "price")
    @Action(input = "http://webservices.sud/ProductsManager/getProductPriceRequest", output = "http://webservices.sud/ProductsManager/getProductPriceResponse", fault = {
        @FaultAction(className = NoSuchProductException_Exception.class, value = "http://webservices.sud/ProductsManager/getProductPrice/Fault/NoSuchProductException")
    })
    public double getProductPrice(
        @WebParam(name = "productId", partName = "productId")
        long productId)
        throws NoSuchProductException_Exception
    ;

    /**
     * 
     * @param product
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "productId", partName = "productId")
    @Action(input = "http://webservices.sud/ProductsManager/addProductRequest", output = "http://webservices.sud/ProductsManager/addProductResponse")
    public long addProduct(
        @WebParam(name = "product", partName = "product")
        Product product);

    /**
     * 
     * @param productId
     * @return
     *     returns sud.webservices.Product
     * @throws NoSuchProductException_Exception
     */
    @WebMethod
    @WebResult(name = "product", partName = "product")
    @Action(input = "http://webservices.sud/ProductsManager/getProductRequest", output = "http://webservices.sud/ProductsManager/getProductResponse", fault = {
        @FaultAction(className = NoSuchProductException_Exception.class, value = "http://webservices.sud/ProductsManager/getProduct/Fault/NoSuchProductException")
    })
    public Product getProduct(
        @WebParam(name = "productId", partName = "productId")
        long productId)
        throws NoSuchProductException_Exception
    ;

    /**
     * 
     * @param productId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.sud/ProductsManager/deleteProductRequest", output = "http://webservices.sud/ProductsManager/deleteProductResponse")
    public boolean deleteProduct(
        @WebParam(name = "productId", partName = "productId")
        long productId);

    /**
     * 
     * @param product
     */
    @WebMethod
    @Action(input = "http://webservices.sud/ProductsManager/updateProductRequest", output = "http://webservices.sud/ProductsManager/updateProductResponse")
    public void updateProduct(
        @WebParam(name = "product", mode = WebParam.Mode.INOUT, partName = "product")
        Holder<Product> product);

    /**
     * 
     * @return
     *     returns sud.webservices.Products
     */
    @WebMethod
    @WebResult(name = "products", partName = "products")
    @Action(input = "http://webservices.sud/ProductsManager/getProductsRequest", output = "http://webservices.sud/ProductsManager/getProductsResponse")
    public Products getProducts();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.sud/ProductsManager/deleteAllProductsRequest", output = "http://webservices.sud/ProductsManager/deleteAllProductsResponse")
    public boolean deleteAllProducts();

}
